# Generated by Django 3.2.4 on 2021-07-01 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departamento_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='tx_nome', max_length=104)),
                ('salario', models.DecimalField(db_column='nb_salario', decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(db_column='cs_ativo', default=True)),
                ('departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='core.departamento')),
            ],
            options={
                'db_table': 'funcionario',
                'managed': True,
            },
        ),
    ]
