# Generated by Django 3.2.4 on 2021-07-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_funcionario_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(blank=True, db_column='cs_sexo', max_length=1, null=True),
        ),
    ]
